<a href="https://colab.research.google.com/github/crispu93/Pytorch_Pocket_Reference/blob/main/2_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## What is a tensor?
Multidimensional array containing values of the same data type, used to represent scalars, vectors, matrices and $n$-dimesional arrays
- Tensors can perform faster using GPU acceleration
- Can be stored and manipulated using distributed processing on multiple CPU's and GPU's across multiple servers
- Keep track of theri graph computations (Automatic differentiation)


## Simple CPU example
By default, the tensor data type will be derived from the input data type and will be allocated on the CPU device.

In [2]:
## Import PyTorch library
import torch

## Create two tensors and add them
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
y = torch.tensor([[7, 8, 9],
                  [10, 11, 12]])
## the class torch.Tensor supports operator overloading
z = x + y
print(z)
print(z.size())

tensor([[ 8, 10, 12],
        [14, 16, 18]])
torch.Size([2, 3])


## Simple GPU example

In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]], device = device)
y = torch.tensor([[7, 8, 9],
                  [9, 10, 11]], device = device)
z = x + y
print(z)
print(z.size())

print(z.device)


tensor([[ 8, 10, 12],
        [13, 15, 17]])
torch.Size([2, 3])
cpu


It is more common to move an existing tensor to a device

In [7]:
device = "cuda" if torch.cuda.is_available() else "cpu"

x = x.to(device)
y = y.to(device)

z = x + y
z.to("cpu")


tensor([[ 8, 10, 12],
        [13, 15, 17]])

## Creating tensors


### From preexisting arrays

In [8]:
import numpy as np

## From a list
w = torch.tensor([1, 2, 3])  
## from a touple
w = torch.tensor((1, 2, 3))
## From a numpy array
w = torch.tensor(np.array([1, 2, 3])) 





### Initialized by size

In [10]:
## Uninitialized, values are not predictable
w = torch.empty(100, 200)
## All elements initialized with 0.0
w = torch.zeros(100, 200)
## All elements initialized by 1.0
w = torch.ones(100, 200)


### Initialized with random values


In [11]:
## Uniform distribution in the interval [0, 1)
w = torch.rand(100, 200)
## Normal distribution with a mean 0 and a variance 1
w = torch.randn(100, 200)
## Elements are random integers between 5 and 10
w = torch.randint(5, 10, (100, 200))

In [15]:
## Initialized with special data type and a specific device
w = torch.empty((100, 200), dtype = torch.float64, device = "cpu")

## Initialized to have the same size, data type and device as another tensor
x = torch.empty_like(w)

## Initialized with ones, to have the same data type, size and device as another tensor
x = torch.ones_like(w)

### Tensor attributes

In [3]:
x = torch.empty(100, 200)

print(x.dtype)
print(x.device)
print(x.shape)
print(x.ndim)
print(x.requires_grad)
print(x.grad)
print(x.grad_fn)

torch.float32
cpu
torch.Size([100, 200])
2
False
None
None
